/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_nge_NGReachability */

#ifndef _Included_com_anansimobile_nge_NGReachability
#define _Included_com_anansimobile_nge_NGReachability
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anansimobile_nge_NGReachability
 * Method:    onNetworkStatusChange
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGReachability_onNetworkStatusChange
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
