/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_nge_NGWebView */

#ifndef _Included_com_anansimobile_nge_NGWebView
#define _Included_com_anansimobile_nge_NGWebView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anansimobile_nge_NGWebView
 * Method:    OnWebViewLoaded
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGWebView_OnWebViewLoaded
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_anansimobile_nge_NGWebView
 * Method:    OnWebViewDismissed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGWebView_OnWebViewDismissed
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
