/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_nge_NGEditTextTextWatcher */

#ifndef _Included_com_anansimobile_nge_NGEditTextTextWatcher
#define _Included_com_anansimobile_nge_NGEditTextTextWatcher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anansimobile_nge_NGEditTextTextWatcher
 * Method:    beforeTextChanged
 * Signature: (ILjava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGEditTextTextWatcher_beforeTextChanged
  (JNIEnv *, jobject, jint, jstring, jint, jint, jint);

/*
 * Class:     com_anansimobile_nge_NGEditTextTextWatcher
 * Method:    onTextChanged
 * Signature: (ILjava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGEditTextTextWatcher_onTextChanged
  (JNIEnv *, jobject, jint, jstring, jint, jint, jint);

/*
 * Class:     com_anansimobile_nge_NGEditTextTextWatcher
 * Method:    getMaxCharacters
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_com_anansimobile_nge_NGEditTextTextWatcher_getMaxCharacters
  (JNIEnv *, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
