/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_nge_NGTextInputConn_ResponderInfo */

#ifndef _Included_com_anansimobile_nge_NGTextInputConn_ResponderInfo
#define _Included_com_anansimobile_nge_NGTextInputConn_ResponderInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
