/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_nge_NGGLSurfaceView */

#ifndef _Included_com_anansimobile_nge_NGGLSurfaceView
#define _Included_com_anansimobile_nge_NGGLSurfaceView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anansimobile_nge_NGGLSurfaceView
 * Method:    onTouchBegin
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGGLSurfaceView_onTouchBegin
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_anansimobile_nge_NGGLSurfaceView
 * Method:    onTouchMoved
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGGLSurfaceView_onTouchMoved
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_anansimobile_nge_NGGLSurfaceView
 * Method:    onTouchEnd
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGGLSurfaceView_onTouchEnd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_anansimobile_nge_NGGLSurfaceView
 * Method:    onTouchCanceled
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGGLSurfaceView_onTouchCanceled
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
