/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_nge_NGAppRater */

#ifndef _Included_com_anansimobile_nge_NGAppRater
#define _Included_com_anansimobile_nge_NGAppRater
#ifdef __cplusplus
extern "C" {
#endif
#undef com_anansimobile_nge_NGAppRater_MSG_POPUP
#define com_anansimobile_nge_NGAppRater_MSG_POPUP 0L
/*
 * Class:     com_anansimobile_nge_NGAppRater
 * Method:    onTapRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGAppRater_onTapRate
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
