/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_nge_NGTextInput */

#ifndef _Included_com_anansimobile_nge_NGTextInput
#define _Included_com_anansimobile_nge_NGTextInput
#ifdef __cplusplus
extern "C" {
#endif
#undef com_anansimobile_nge_NGTextInput_MSG_VIEW_NUMBER_ONLY
#define com_anansimobile_nge_NGTextInput_MSG_VIEW_NUMBER_ONLY 5L
#ifdef __cplusplus
}
#endif
#endif
