/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_nge_NGTextInputConn */

#ifndef _Included_com_anansimobile_nge_NGTextInputConn
#define _Included_com_anansimobile_nge_NGTextInputConn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anansimobile_nge_NGTextInputConn
 * Method:    nativeCommitText
 * Signature: (ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGTextInputConn_nativeCommitText
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_anansimobile_nge_NGTextInputConn
 * Method:    nativeSendKeyEvent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGTextInputConn_nativeSendKeyEvent
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
