/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_nge_NextGenEngine */

#ifndef _Included_com_anansimobile_nge_NextGenEngine
#define _Included_com_anansimobile_nge_NextGenEngine
#ifdef __cplusplus
extern "C" {
#endif
#undef com_anansimobile_nge_NextGenEngine_SYSTEMFONT_MODE_FILL
#define com_anansimobile_nge_NextGenEngine_SYSTEMFONT_MODE_FILL 0L
#undef com_anansimobile_nge_NextGenEngine_SYSTEMFONT_MODE_STROKE
#define com_anansimobile_nge_NextGenEngine_SYSTEMFONT_MODE_STROKE 1L
#undef com_anansimobile_nge_NextGenEngine_SYSTEMFONT_MODE_FILLSTROKE
#define com_anansimobile_nge_NextGenEngine_SYSTEMFONT_MODE_FILLSTROKE 2L
#undef com_anansimobile_nge_NextGenEngine_STRING_TEXTURE_CACHE_LIMIT
#define com_anansimobile_nge_NextGenEngine_STRING_TEXTURE_CACHE_LIMIT 2048L
/*
 * Class:     com_anansimobile_nge_NextGenEngine
 * Method:    bitmapDataDidLoad
 * Signature: (ILandroid/graphics/Bitmap;II)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NextGenEngine_bitmapDataDidLoad
  (JNIEnv *, jclass, jint, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
