/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_nge_RootActivity */

#ifndef _Included_com_anansimobile_nge_RootActivity
#define _Included_com_anansimobile_nge_RootActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_anansimobile_nge_RootActivity_UI_MSG_ALERT
#define com_anansimobile_nge_RootActivity_UI_MSG_ALERT 1200L
#undef com_anansimobile_nge_RootActivity_UI_MSG_TEXTINPUT
#define com_anansimobile_nge_RootActivity_UI_MSG_TEXTINPUT 1300L
#undef com_anansimobile_nge_RootActivity_UI_MSG_APPRATER
#define com_anansimobile_nge_RootActivity_UI_MSG_APPRATER 1910L
/*
 * Class:     com_anansimobile_nge_RootActivity
 * Method:    onGamePause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_RootActivity_onGamePause
  (JNIEnv *, jobject);

/*
 * Class:     com_anansimobile_nge_RootActivity
 * Method:    onGameResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_RootActivity_onGameResume
  (JNIEnv *, jobject);

/*
 * Class:     com_anansimobile_nge_RootActivity
 * Method:    HandleSystemBackEvent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_RootActivity_HandleSystemBackEvent
  (JNIEnv *, jobject);

/*
 * Class:     com_anansimobile_nge_RootActivity
 * Method:    setSystemUIFrame
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_RootActivity_setSystemUIFrame
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
