/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_nge_NGLocation */

#ifndef _Included_com_anansimobile_nge_NGLocation
#define _Included_com_anansimobile_nge_NGLocation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_anansimobile_nge_NGLocation_LOCATION_MSG_REQUEST
#define com_anansimobile_nge_NGLocation_LOCATION_MSG_REQUEST 1001L
/*
 * Class:     com_anansimobile_nge_NGLocation
 * Method:    requestLocationSuccess
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGLocation_requestLocationSuccess
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     com_anansimobile_nge_NGLocation
 * Method:    requestLocationFailed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGLocation_requestLocationFailed
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
