/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_nge_NGImagePicker */

#ifndef _Included_com_anansimobile_nge_NGImagePicker
#define _Included_com_anansimobile_nge_NGImagePicker
#ifdef __cplusplus
extern "C" {
#endif
#undef com_anansimobile_nge_NGImagePicker_REQ_PIC_FROM_ALBUM
#define com_anansimobile_nge_NGImagePicker_REQ_PIC_FROM_ALBUM 3001L
#undef com_anansimobile_nge_NGImagePicker_REQ_PIC_FROM_CAMERA
#define com_anansimobile_nge_NGImagePicker_REQ_PIC_FROM_CAMERA 3002L
#undef com_anansimobile_nge_NGImagePicker_REQ_PIC_FROM_EDITOR
#define com_anansimobile_nge_NGImagePicker_REQ_PIC_FROM_EDITOR 3003L
/*
 * Class:     com_anansimobile_nge_NGImagePicker
 * Method:    bitmapDidScaled
 * Signature: (ILandroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGImagePicker_bitmapDidScaled
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_anansimobile_nge_NGImagePicker
 * Method:    bitmapDataDidScaled
 * Signature: (I[BIII)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGImagePicker_bitmapDataDidScaled
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jint);

/*
 * Class:     com_anansimobile_nge_NGImagePicker
 * Method:    bitmapDidLoad
 * Signature: (ILandroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGImagePicker_bitmapDidLoad
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_anansimobile_nge_NGImagePicker
 * Method:    bitmapDataDidLoad
 * Signature: (I[BIII)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGImagePicker_bitmapDataDidLoad
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
