/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_nge_NGAlertDialog */

#ifndef _Included_com_anansimobile_nge_NGAlertDialog
#define _Included_com_anansimobile_nge_NGAlertDialog
#ifdef __cplusplus
extern "C" {
#endif
#undef com_anansimobile_nge_NGAlertDialog_UI_MSG_TEXT_ALERT
#define com_anansimobile_nge_NGAlertDialog_UI_MSG_TEXT_ALERT 0L
#undef com_anansimobile_nge_NGAlertDialog_UI_MSG_WAITING_ALERT
#define com_anansimobile_nge_NGAlertDialog_UI_MSG_WAITING_ALERT 1L
/*
 * Class:     com_anansimobile_nge_NGAlertDialog
 * Method:    onAlertDialogButtonClick
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGAlertDialog_onAlertDialogButtonClick
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
