/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_nge_NGHttpSession */

#ifndef _Included_com_anansimobile_nge_NGHttpSession
#define _Included_com_anansimobile_nge_NGHttpSession
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
