/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_nge_NGWebView_NGWebChromeClient */

#ifndef _Included_com_anansimobile_nge_NGWebView_NGWebChromeClient
#define _Included_com_anansimobile_nge_NGWebView_NGWebChromeClient
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
