/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_nge_IAB_NGStoreKit */

#ifndef _Included_com_anansimobile_nge_IAB_NGStoreKit
#define _Included_com_anansimobile_nge_IAB_NGStoreKit
#ifdef __cplusplus
extern "C" {
#endif
#undef com_anansimobile_nge_IAB_NGStoreKit_STOREKIT_REQ_PURCHASE
#define com_anansimobile_nge_IAB_NGStoreKit_STOREKIT_REQ_PURCHASE 4001L
/*
 * Class:     com_anansimobile_nge_IAB_NGStoreKit
 * Method:    shouldConsumeProduct
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_anansimobile_nge_IAB_NGStoreKit_shouldConsumeProduct
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_anansimobile_nge_IAB_NGStoreKit
 * Method:    OnPurchaseFinished
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_IAB_NGStoreKit_OnPurchaseFinished
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_anansimobile_nge_IAB_NGStoreKit
 * Method:    OnPaymentFailed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_IAB_NGStoreKit_OnPaymentFailed
  (JNIEnv *, jclass);

/*
 * Class:     com_anansimobile_nge_IAB_NGStoreKit
 * Method:    OnProduct
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_IAB_NGStoreKit_OnProduct
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_anansimobile_nge_IAB_NGStoreKit
 * Method:    OnProductListFinished
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_IAB_NGStoreKit_OnProductListFinished
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
