/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_nge_NGStringHelper */

#ifndef _Included_com_anansimobile_nge_NGStringHelper
#define _Included_com_anansimobile_nge_NGStringHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anansimobile_nge_NGStringHelper
 * Method:    AddStringLine
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGStringHelper_AddStringLine
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_anansimobile_nge_NGStringHelper
 * Method:    UpdateLineHeight
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_nge_NGStringHelper_UpdateLineHeight
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_anansimobile_nge_NGStringHelper
 * Method:    WordStartFlag
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_anansimobile_nge_NGStringHelper_WordStartFlag
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_anansimobile_nge_NGStringHelper
 * Method:    WordEndFlag
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_anansimobile_nge_NGStringHelper_WordEndFlag
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
