/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anansimobile_extra_social_weixin_WXHelper */

#ifndef _Included_com_anansimobile_extra_social_weixin_WXHelper
#define _Included_com_anansimobile_extra_social_weixin_WXHelper
#ifdef __cplusplus
extern "C" {
#endif
#undef com_anansimobile_extra_social_weixin_WXHelper_THUMB_SIZE
#define com_anansimobile_extra_social_weixin_WXHelper_THUMB_SIZE 150L
/*
 * Class:     com_anansimobile_extra_social_weixin_WXHelper
 * Method:    OnSendMsgToWXDone
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_extra_social_weixin_WXHelper_OnSendMsgToWXDone
  (JNIEnv *, jclass);

/*
 * Class:     com_anansimobile_extra_social_weixin_WXHelper
 * Method:    OnSendMsgToWXCanceled
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_extra_social_weixin_WXHelper_OnSendMsgToWXCanceled
  (JNIEnv *, jclass);

/*
 * Class:     com_anansimobile_extra_social_weixin_WXHelper
 * Method:    OnSendMsgToWXFailed
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_anansimobile_extra_social_weixin_WXHelper_OnSendMsgToWXFailed
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
